<?php

use Illuminate\Database\Seeder;

class ExpertiseTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data =  
        '[
        {
            "id": 3,
            "category_id": 5,
            "slug": "gretchen-gayecablanza",
            "first_name": "Gretchen Gaye",
            "middle_name": "C.",
            "last_name": "Ablanza",
            "image": "1615960327-ggablaza.png",
            "email": "giavalyn81@gmail.com",
            "position": "Assistant Professor I",
            "office": "Institute of Public Administration- Benguet State University",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p>Public Administration</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Governance, leadership, development, management of organizations, and public personnel administration.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p>Qualitative Research</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Background, theoretical underpinnings of Qualitative Longitudinal Research.</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Different kinds of Qualitative Longitudinal Research.</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Data analysis and interpretation of Qualitative Longitudinal Research.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p>Positive Organization Behavior</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Developing hope, optimism, and resilience</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Positivity in the workplace</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 4,
            "category_id": 5,
            "slug": "judithradina",
            "first_name": "Judith",
            "middle_name": "R.",
            "last_name": "Adina",
            "image": "1615960389-jradina.png",
            "email": "adinajudith@yahoo.com",
            "position": "Guidance Counselor",
            "office": "Baguio Central University",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p>Guidance Counselling</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Parenting</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Leadership</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Team Building</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Academic Concerns in Stress and Time Management</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 5,
            "category_id": 5,
            "slug": "hooveragyao",
            "first_name": "Hoover",
            "middle_name": null,
            "last_name": "Agyao",
            "image": "1615960474-hagyao.png",
            "email": "hooveragyao@rocketmail.com",
            "position": "V.P for External Relations | Professor | Director",
            "office": "Cordillera Career Development College",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p>Community Organizing</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Team Building</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Coaching</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Public Speaking</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Research</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Monitoring and evaluation</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 6,
            "category_id": 5,
            "slug": "ma-lourdesrosalaurelio",
            "first_name": "Ma. Lourdes",
            "middle_name": "Rosal",
            "last_name": "Aurelio",
            "image": "1615960586-mlraurelio.png",
            "email": "malou_aurelio@yahoo.com",
            "position": "Professor (Social Worker)",
            "office": "Union Christian College",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p><strong>A Social Work-Related</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Casework and case management, community organizing, policy making, and gender and development.</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Supervision and administration</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Trainings</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Family concerns, leadership, livelihood, and project monitoring and evaluation.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 7,
            "category_id": 5,
            "slug": "ameliacendana",
            "first_name": "Amelia",
            "middle_name": null,
            "last_name": "Cendana",
            "image": "1615960819-acendana.png",
            "email": "accendana@up.edu.ph",
            "position": "Chief Librarian",
            "office": "University of the Philippines-Baguio",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p><strong>Library Management</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Cataloging, Classification, Record Management</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Cooperative Management</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Management and Policies regarding cooperative/ multi-purpose.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Seminar in Library Organizations</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Organize local, regional and national conference, seminars and trainings.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 8,
            "category_id": 5,
            "slug": "sandra-lynnbgatayen",
            "first_name": "Sandra Lynn",
            "middle_name": "B.",
            "last_name": "Gatayen",
            "image": "1615960946-slbgatayen.jpg",
            "email": "sgatayen@gmail.com",
            "position": "Dean | College of Social Work",
            "office": "Cordillera Career Development College",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p><strong>Grassroots Communication and Mobilizing</strong></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Community Organizing </strong></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Social Case Management</strong></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Program Management</strong></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Relationship Building</strong></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Program Coordination</strong></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Team Building/Leadership</strong></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 9,
            "category_id": 5,
            "slug": "laurenpkipaan",
            "first_name": "Lauren",
            "middle_name": "P.",
            "last_name": "Kipaan",
            "image": "1615961008-lpkipaan.png",
            "email": "l.kipaan@bsu.edu.ph",
            "position": "Library Director",
            "office": "Benguet State University Library and Information Services",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p>Library Automation</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>Integrated Library System (ILS)</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>Networking technologies in the library</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p>Digitization of Records and Books</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>Library Management System</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p>Setting up of Journal and Repository System</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 10,
            "category_id": 5,
            "slug": "florencehliccud",
            "first_name": "Florence",
            "middle_name": "H.",
            "last_name": "Liccud",
            "image": "1615961062-fhliccud.png",
            "email": "liccudf@yahoo.com",
            "position": "Assistant Professor III | Adviser",
            "office": "Saint Louis University | PRIME Movers Society",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p><strong>Group Work &amp; Community Organizing</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>The Helping Process in Social Group Work</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Phases of Community Organization Process.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Rural Development</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Simple Project/ Program Development and Management</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 11,
            "category_id": 5,
            "slug": "mary-paulineenamoca",
            "first_name": "Mary Pauline",
            "middle_name": "E.",
            "last_name": "Namoca",
            "image": "1615961177-namoca.png",
            "email": "paunamoca@gmail.com",
            "position": "Professor | Psychologist",
            "office": "Saint Louis University",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p><strong>Psychological Assessment</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Psychological assessment for children, adolescents, and adults which includes, but are not limited to personality, psychological difficulties, achievement and ability, and neurological functioning. </em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Clinical Counselling &amp; Psychotherapy</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Provides counselling services and assistance for various personal, social, and psychological difficulties and provides diagnosis and diverse psychotherapeutic techniques when called for.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Research</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Conducts psychological research in the development of programs and assessment tools that will better mental health practices.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Seminars and Training</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>May provide training on various topics related to mental health and psychological assessment. </em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 12,
            "category_id": 5,
            "slug": "nathaliepmalabato-saguido",
            "first_name": "Nathalie",
            "middle_name": "P.",
            "last_name": "Malabato-Saguido",
            "image": "1615961265-saguido.png",
            "email": "nathalie.malabato@gmail.com",
            "position": "Project Coordinator",
            "office": "Center for Disaster Preparedness",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p><strong>Community-Based Disaster Risk Reduction and Management </strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Learning, sharing and knowledge creation;</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Good practice and success stories documentation </em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Module Development</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Develop framework and training designs.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Facilitation / Planning</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Supports collaborative work processes.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 13,
            "category_id": 5,
            "slug": "annielynbofo-ob",
            "first_name": "Annielyn",
            "middle_name": "B.",
            "last_name": "Ofo-ob",
            "image": "1615961343-annielyn.png",
            "email": "annie.ofoob@gmail.com",
            "position": "Faculty",
            "office": "Cordillera Career Development College",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 14,
            "category_id": 5,
            "slug": "rojanapaleng",
            "first_name": "Rojan",
            "middle_name": "A.",
            "last_name": "Paleng",
            "image": "1615961557-rapaleng.png",
            "email": "rapaleng@up.edu.ph",
            "position": "Librarian",
            "office": "University of the Philippines-Baguio",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p><strong>Knowledge Management</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Learning, sharing and knowledge creation; Good practice and success stories documentation </em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Library Management</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Common Library Construct, Planning and Maintaining Library Facilities, Associations and Publications</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Integrated Library System (ILS) Management</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Library Software applications (MARC-21 Compliant)</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Records Management</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Modern records management applications including records development policy creation</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Learning and Development</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Facilitation and learning management, hosting and activity documentation</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 15,
            "category_id": 6,
            "slug": "ana-karinaalamsen",
            "first_name": "Ana Karina",
            "middle_name": "A.",
            "last_name": "Lamsen",
            "image": "1615961629-akalamsen.png",
            "email": "ina.albero@yahoo.com.ph",
            "position": "Training Specialist II",
            "office": "DOH Center for Health Development- CAR",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 16,
            "category_id": 7,
            "slug": "virgilioablanza",
            "first_name": "Virgilio",
            "middle_name": null,
            "last_name": "Ablanza",
            "image": "1615961723-vablaza.png",
            "email": "ablazajrtc@gmail.com",
            "position": "Dean | President",
            "office": "College of Criminology, Easter College |  Johanna Research Training Center",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p><strong>Public Safety and Security</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Juvenile justice administration, local government and safety administration.</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Criminal justice and law enforcement administration.</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Public policy development.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Qualitative Research</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Social Science and Criminological Research</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p><strong>Community and Organizational Development</strong></p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Organization, management, and leadership.</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 17,
            "category_id": 7,
            "slug": "julitapontanares",
            "first_name": "Julita",
            "middle_name": null,
            "last_name": "Pontanares",
            "image": "1615961773-jpontanares.png",
            "email": "j.pontanares@yahoo.com.ph",
            "position": "Social Worker",
            "office": "Purple Centers Foundation",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 18,
            "category_id": 7,
            "slug": "jonathandsantiago",
            "first_name": "Jonathan",
            "middle_name": "D.",
            "last_name": "Santiago",
            "image": "1615961844-jsantiago.jpg",
            "email": "jdsantiago.cpfi@yahoo.com.ph",
            "position": "Federation Manager",
            "office": "Cordillera Parent`s Federation, Inc.",
            "content": "<p><em><strong>Specialization:</strong></em><ul>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 19,
            "category_id": 8,
            "slug": "florencehliccud",
            "first_name": "Florence",
            "middle_name": "H.",
            "last_name": "Liccud",
            "image": "1615961915-slu.jpg",
            "email": "slu@yahoo.com",
            "position": null,
            "office": "Saint Louis University",
            "content": "<p><small>Saint Louis University is regarded as one of the Philippines` respected and leading educational institutions that has grown with the demands of the current and future environments for its students and faculty alike.</small><p><strong>POTENTIAL CONTRIBUTION TO THE NETWORK:</strong></p><ul>\r\n\t<li>\r\n\t<p>Partnerships in Programs and Activities for Social Welfare and Development</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Resource Person ad Subject Matter Experts for seminars, forums, trainings, and workshops</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Expertise in Research, Education and outreach programs for social welfare and development</p>\r\n\t</li>\r\n</ul><p><strong>INSTITUTIONAL DEVELOPMENT AND CAPACITY BUILDING SERVICES:</strong></p><ul>\r\n\t<li>\r\n\t<p>Continuing professional education training workshop for all staffs</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Scholarship grants to qualified staffs for higher education within the Philippines and abroad</p>\r\n\t</li>\r\n</ul><p><strong>AVAILABLE RESOURCES (that can be shared to the network)</strong></p><ul>\r\n\t<li>\r\n\t<p>Human Resource</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Physical Facilities</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 20,
            "category_id": 8,
            "slug": "jayfordpaet",
            "first_name": "Jayford",
            "middle_name": null,
            "last_name": "Paet",
            "image": "1615961965-tebtebba.jpg",
            "email": "tebtebba@tebtebba.org",
            "position": null,
            "office": "Tebtebba Foundation",
            "content": "<p><small>Tebtebba is an indigenous peoples` organization and a research, education, policy advocacy and resource center working with indigenous peoples at all levels and areas. They seek the recognition, promotion and protection of indigenous peoples` rights and aspirations while building unions to uphold social and environmental justice and sustainability.</small><p><strong>POTENTIAL CONTRIBUTION TO THE NETWORK:</strong></p><ul>\r\n\t<li>\r\n\t<p>Provide resource speakers and subject matter experts for Indigenous peoples issues and relevant information:</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>IPs Rights</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>IPs and Climate Change</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>IPs and Gender</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>IPs and Sustainable Development</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>IPs and Biodiversity and others</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul><p><strong>INSTITUTIONAL DEVELOPMENT AND CAPACITY BUILDING SERVICES:</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>Training and Workshops for Indigenous People`s issues and concerns.</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul><p><strong>AVAILABLE RESOURCES (that can be shared to the network)</strong></p><ul>\r\n\t<li>\r\n\t<p>Learning Resource Materials for researches and information.</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Expertise to issues and concerns about Indigenous Peoples</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>can be a resource person / subject matter expert in seminars, forums, conventions and trainings.</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 21,
            "category_id": 8,
            "slug": "virgilioablaza",
            "first_name": "Virgilio",
            "middle_name": null,
            "last_name": "Ablaza",
            "image": "1615962021-johanna-research.jpg",
            "email": "ablazajrtc@gmail.com",
            "position": null,
            "office": "Johanna Research and Training Center",
            "content": "<p><small>The Johanna Research and Training Center caters to students, professional scholars, youth, government officials, leaders and community. The center&rsquo;s areas of concerns are research, training, board review and social services.</small><p><strong>POTENTIAL CONTRIBUTION TO THE NETWORK:</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>Develop and enhance the culture of research within the students and young professionals within the region.</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>Conduct necessary training and quality researches that has influence to the Asian and international community.</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>Initiate and conduct researches and training that will directly benefit the life Filipino people.</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>Utilize research and training as a tool in promoting inclusive development learning and preserving the rich culture of the Filipino people.</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>Provide training and technical assistance to students and local researchers.</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul><p><strong>INSTITUTIONAL DEVELOPMENT AND CAPACITY BUILDING SERVICES:</strong></p><ul>\r\n\t<li>\r\n\t<p>Conduct of capacity building on qualitative research through a series of training workshop on qualitative research in the City of Palawan and Baguio.</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Conduct of Training on how to productively perform duties and responsibilities as newly elected officials in the government. (Both Barangay and SK officials)</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Provision of Continuing Professional Development to teachers and criminologist.</p>\r\n\t</li>\r\n</ul><p><strong>AVAILABLE RESOURCES (that can be shared to the network)</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>Human resource &ndash; we can share our expertise in line with our organizational operations, we can share our knowledge and skills regarding training, researches and the different expertise of our member in their different professions.</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 22,
            "category_id": 8,
            "slug": "",
            "first_name": null,
            "middle_name": null,
            "last_name": null,
            "image": "1615962082-new-media-services.jpg",
            "email": "info@nms-cares.org",
            "position": null,
            "office": "New Media Services-Cares, Inc.",
            "content": "<p><small>NMS-Cares is a nonprofit organization registered and incorporated with the Philippine Securities and Exchange Commission (SEC) August of 2014 with registration number CN201427490. It started as a corporate social responsibility initiative to help Deaf children&rsquo;s education in 2012 by Martin Eyking and his family, founder and CEO of New Media Services Pty. Ltd., an Australian-based IT company with operations in the Philippines.</small><p><strong>POTENTIAL CONTRIBUTION TO THE NETWORK:</strong></p><ul>\r\n\t<li>\r\n\t<p>Organization of Training for:</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<ul>\r\n\t\t\t<li>\r\n\t\t\t<p>Sign Language Seminars and Forums</p>\r\n\t\t\t</li>\r\n\t\t\t<li>\r\n\t\t\t<p>Deaf Awareness</p>\r\n\t\t\t</li>\r\n\t\t</ul>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p>Provide a Subject Matter Experts on Seminars, Forums, Training and Workshops concerning matters critical to the deaf community.</p>\r\n\t</li>\r\n</ul><p><strong>INSTITUTIONAL DEVELOPMENT AND CAPACITY BUILDING SERVICES:</strong></p><ul>\r\n\t<li>\r\n\t<p>Conduct of Sign Language Skills Training</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Conduct of Deaf Awareness and Sensitivity Training, Seminars and Forums</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Conduct of Deaf Sports Development</p>\r\n\t</li>\r\n</ul><p><strong>AVAILABLE RESOURCES (that can be shared to the network)</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>Human resource &ndash; we can share our expertise in line with Deaf Awareness, Sensitivity Training and Seminars, Sign Language Skills Development and Disability Advocacies.</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 23,
            "category_id": 8,
            "slug": "",
            "first_name": null,
            "middle_name": null,
            "last_name": null,
            "image": "1615962137-helping-hands.png",
            "email": "info@helpinghandsministries.com",
            "position": null,
            "office": "Helping Hands Healing Hearts Ministries Philippines, Inc.",
            "content": "<p><small>Helping Hands Healing Hearts Ministries Philippines Inc. (HHM) began in 2001 in response to the needs of sick Filipino children. Claire Henderson had gone to the Philippines in 1998 for a 6 month mission trip but quickly realised that God had more work planned for her do. She began HHM after watching a child die a horrific death from rabies, following a dog bite. His parents wept as they explained that they just couldn&rsquo;t afford the injections that would have saved his life. He needed medications. He needed a miracle. Claire started simply, by helping provide medications in the hospital to the children and families who could not afford them. Saving their lives, being there for them in their hour of need and bringing the love and the hope of Jesus to them was her mission. After a few years she began their first Children&rsquo;s Recovery Unit (CRU) in Olongapo City. Another followed four years later in Baguio City and most recently HHM adopted a whole orphanage.</small><p><strong>POTENTIAL CONTRIBUTION TO THE NETWORK:</strong></p><ul>\r\n\t<li>\r\n\t<p>Programs and Activities regarding Children&rsquo;s Welfare.</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Good practices in handling children</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Assist in crafting policies and programs for the benefit of the children .</p>\r\n\t</li>\r\n</ul><p><strong>INSTITUTIONAL DEVELOPMENT AND CAPACITY BUILDING SERVICES:</strong></p><ul>\r\n\t<li>\r\n\t<p>Internal Capacity Building &ndash; Provides adequate support for improving staff competencies, design appropriate management systems and making available the required logistics to further our cause in promoting and safeguarding the rights and welfare of children.</p>\r\n\t</li>\r\n</ul><p><strong>AVAILABLE RESOURCES (that can be shared to the network)</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>Human resource for future engagements as resource speakers and subject matter experts.</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 24,
            "category_id": 8,
            "slug": "",
            "first_name": null,
            "middle_name": null,
            "last_name": null,
            "image": "1615962249-fil-jap-foundation.png",
            "email": "fjfnli@gmail.com",
            "position": null,
            "office": "Filipino-Japanese Foundation of Northern Luzon, Inc.  (Abong)",
            "content": "<p><small>In October 1970, Sister Theresia Unno enplaned along with other Japanese religious who came to see Pope Paul VI on his visit to the Philippines. This visit drew her attention to plight of many poor Filipinos living in Tondo. This was a moment in her life she knew was the realization of her dream, to help needy people in a foreign land. </small><br>\r\n<small>The idea of a Filipino-Japanese Association was born when she made her decision to seek and gather Japanese descendants orphaned by the thousands of Japanese who labored in the construction of Kennon Road.</small><br>\r\n<small>On June 2, 1983, the Association was duly registered with the Securities and Exchange Commission under the name Filipino-Japanese Friendship Association of Northern Luzon, Inc. (FJFANLI).</small><br>\r\n<small>Having gathered her flocked of Japanese descendants, Sr. Unno was faced next with the challenge to uplift the quality of life of these descendants. From her encounters with them she learned that providing education to their children was more of a problem rather than poverty itself. Based on this finding, she set on another mission to help provide education for the younger generation. With this new mission, the good Sister sought the help of her many benefactor friends and donors in Japan. In no time, an outpour of support came from various civic minded individuals and groups, veteran`s groups, and religious organizations in Japan. A scholarship committee was formed, and seven (7) college students emerged as the first beneficiaries. From a modest beginning of seven scholars, the number swelled to several hundreds.</small><br>\r\n<small>In November 1987 a building and lot at No. 3 Bukaneg Street, Legarda Road, Baguio City was acquired by Sr. Unno for and in behalf of the FJFANLI. The place is now commonly known as \"Abong\", a native word meaning \"small house\". Though big in structure, it is truly a small house to accommodate the ever-increasing members of the FJFANLI. Abong now stands as another monument of Sr. Theresia Unno especially in the hearts of each member. Later, the name of Filipino-Japanese Foundation of Northern Luzon Inc. was adopted. It was duly licensed in 1995 by the Department of Social Welfare and Development (DSWD) as a Non-Government Organization (NGO) to operate as a youth and family Social Welfare Agency. The Foundation is also duly accredited as Civil Society Organization (CSO) by the City of Baguio.</small><p><strong>POTENTIAL CONTRIBUTION TO THE NETWORK:</strong></p><ul>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n</ul><p><strong>INSTITUTIONAL DEVELOPMENT AND CAPACITY BUILDING SERVICES:</strong></p><ul>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n</ul><p><strong>AVAILABLE RESOURCES (that can be shared to the network)</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>&nbsp;</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 25,
            "category_id": 8,
            "slug": "",
            "first_name": null,
            "middle_name": null,
            "last_name": null,
            "image": "1615962397-bsu.png",
            "email": "web.admin@bsu.edu.ph",
            "position": null,
            "office": "Benguet State University",
            "content": "<p><small>Benguet State University is nestled in the heart of La Trinidad, Benguet, the strawberry capital of the Philippines.</small><small>It started as the La Trinidad Farm School with 30 grade V pupils in 1916. The Farm School expanded its services and heightened its prominence in La Trinidad. According to earlier reports, the Farm School was &ldquo;planned to develop into a large normal school where the best Igorot pupils will be trained to be teachers among their own people with emphasis on agriculture.&rdquo;</small><p><strong>POTENTIAL CONTRIBUTION TO THE NETWORK:</strong></p><ul>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n</ul><p><strong>INSTITUTIONAL DEVELOPMENT AND CAPACITY BUILDING SERVICES:</strong></p><ul>\r\n\t<li>\r\n\t<p>&nbsp;</p>\r\n\t</li>\r\n</ul><p><strong>AVAILABLE RESOURCES (that can be shared to the network)</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>&nbsp;</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 26,
            "category_id": 1,
            "slug": "amelynpcabrera",
            "first_name": "Amelyn",
            "middle_name": "P.",
            "last_name": "Cabrera",
            "image": "1615963703-mam-amy.jpg",
            "email": "apcabrera@dswd.gov.ph",
            "position": "Social Welfare Officer V",
            "office": "OIC Assistant Regional Director for Operations",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p>Master of Arts in Social Work (12 units) University of Northern Philippines, 2017</p><p><em><strong>Specialization:</strong></em></p><ol>\r\n\t<li>\r\n\t<p>Children Welfare</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Day Care Services</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Alternative Parental Care</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Case Management</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p>Program Management</p>\r\n\t</li>\r\n</ol><p><em>A. Implementation of Social Pension Program</em></p><ul>\r\n\t<li>\r\n\t<p><em>Validation of Qualified Social Pensioners</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Republic Act 9994 also known as &ldquo;The Expanded Senior Citizen Act of 2010</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Administration of the Social Pension Pay-out</em></p>\r\n\t</li>\r\n</ul><p><em>B. Implementation of the Centenarian </em><em> </em><em>Program</em></p><ol>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Republic Act 10868 also known as &ldquo;Centenarian&rsquo;s Act of 2006&rdquo;</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Assessment of Qualified Centenarians</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Centenarian&rsquo;s Act</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n\t<li>\r\n\t<p>Case Management</p>\r\n\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Social Case Study Reporting</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Helping Process and problem solving</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Evaluation and Termination of Cases</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ol></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 27,
            "category_id": 1,
            "slug": "judithlde-guzman",
            "first_name": "Judith",
            "middle_name": "L.",
            "last_name": "De Guzman",
            "image": "1615963861-mam-judith.jpg",
            "email": "jldeguzman@dswd.gov.ph",
            "position": "Social Welfare Officer IV",
            "office": "Crisis Intervention Section Head",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p>Bachelor of Science in Social Work (Saint Louis University, 1981)</p><p><em><strong>Specialization:</strong></em></p><ol>\r\n\t<li>\r\n\t<p>Children Welfare</p>\r\n\t</li>\r\n</ol><ul>\r\n\t<li>\r\n\t<p>Adoption</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Foster Care</p>\r\n\t</li>\r\n</ul><ol>\r\n\t<li>\r\n\t<p>Crisis Intervention</p>\r\n\t</li>\r\n</ol><ul>\r\n\t<li>\r\n\t<p><em>Assessment and Planning</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Resource Mobilization</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Selection of Interventive Roles</em></p>\r\n\t</li>\r\n</ul><ol>\r\n\t<li>\r\n\t<p>Case Management</p>\r\n\t</li>\r\n</ol><ul>\r\n\t<li>\r\n\t<p><em>Social Case Study</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Helping Process and Problem Solving</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Evaluation and Termination of Cases</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 28,
            "category_id": 1,
            "slug": "mary-anngbuclao",
            "first_name": "Mary Ann",
            "middle_name": "G.",
            "last_name": "Buclao",
            "image": "1615963985-mam-mary-ann.jpg",
            "email": "magbuclao.focar@dswd.gov.ph",
            "position": "Social Welfare Officer IV",
            "office": "OIC Division Chief Disaster Response and Management Division",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><ul>\r\n\t<li>\r\n\t<p>Diploma in Project Management (Technical Institute of the Philippine Center, 2011)</p>\r\n\t</li>\r\n</ul><ul>\r\n\t<li>\r\n\t<p>Bachelor of Laws and Letters (University of the Cordilleras, 2005)</p>\r\n\t</li>\r\n</ul><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Children, Elderly, Family Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Case Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Child Placement (Adoption, Legal Guardianship, Foster Care, and Residential Institutional Care)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Parent Effectiveness</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Strengthening of Family Values and&nbsp; Preservation of Cultural Heritage</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Gerontology</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Disaster Risk Reduction and Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Disaster Preparedness</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Disaster Prevention and Mitigation</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Disaster Response</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Incident Command System</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Camp Coordination and Camp Management</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 29,
            "category_id": 1,
            "slug": "carmencitalchaluyen",
            "first_name": "Carmencita",
            "middle_name": "L.",
            "last_name": "Chaluyen",
            "image": "1615964070-mam-carmen.jpg",
            "email": "clchaluyen@dswd.gov.ph",
            "position": "Social Welfare Officer II",
            "office": "SWAD Team Leader- Abra",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters of Arts in Social Work (Asian Social Institute, 2010)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Children Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Organizing and strengthening the Local Council for the protection of Children (BCPC)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Criteria and identification of Presidential Award for Child&ndash; Friendly Municipalities and Cities</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Rights of Children</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Youth Welfare Program along Unlad Kabataan Program</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Population and Family Life Orientation (PAFLO)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Organizing Pagasa Youth Association</em></p>\r\n\t</li>\r\n</ul><p><em><strong>2. </strong></em><strong>Person with Disabilities Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Administration and resource mobilization</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Case management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>PWD Rights and Privileges</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Anti-discrimination advocacies for PWDs</em></p>\r\n\t</li>\r\n</ul><p><strong>3. </strong><strong>Women Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Community Education for the acceptance of socially disadvantage women</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Research and Advocacy for the Protection of Women and their Children</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Rights and Privileges of Women</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 30,
            "category_id": 1,
            "slug": "fatimadflorendo",
            "first_name": "Fatima",
            "middle_name": "D.",
            "last_name": "Florendo",
            "image": "1615964129-mam-fatz.jpg",
            "email": "fdflorendo@dswd.gov.ph",
            "position": "Project Development Officer V",
            "office": "Regional Program Coordinator: Pantawid Pamilyang Pilipino Program",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters of Social Work (University of Northern Philippines, 2016)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1.</strong> <strong>Children and Family Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Social Case Study Reports</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Violence Against Women and Children Laws</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Prevention of Child Sexual Abuse</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Improvement and Strengthening Family Support among Members</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Parent Effectiveness and Parenting Skills</em></p>\r\n\t</li>\r\n</ul><p><strong>2.</strong> <strong>Gender and Development</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Gender Sensitivity</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Community Education for the awareness of the LGBTQ Community</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Rights and Protection for LGBTQs</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Gender and Development on Camp Coordination and Camp Management</em></p>\r\n\t</li>\r\n</ul><p><strong>3. </strong><strong>Program Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Implementation of the Republic Act 11310 or also known as &ldquo;An Act Institutionalizing the Pantawid Pamilyang Pilipino Program (4Ps)&rdquo;</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Orientation on Rules and Guidelines for the Pantawid Pamilyang Pilipino Program (4Ps)</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 31,
            "category_id": 1,
            "slug": "bonafegramos",
            "first_name": "Bonafe",
            "middle_name": "G.",
            "last_name": "Ramos",
            "image": "1615964185-mam-bona.jpg",
            "email": "bbramos@dswd.gov.ph",
            "position": "Training Specialist I",
            "office": "Learning and Development Section Head",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Bachelor of Science in Psychology (Don Mariano Marcos Memorial State University-South La Union Campus , 2011)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1.</strong> <strong>Children and Family Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Psychosocial Interventions for Children and Youth</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Stress/ Trauma Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Counselling</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Psychological Assessment</em></p>\r\n\t</li>\r\n</ul><p><strong>2.</strong> <strong>Learning and Development</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Professional Management and Development</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Career Development Plan</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Bayanihang Bayan Program</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Training and Activities for Employees</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 32,
            "category_id": 1,
            "slug": "rojhelia-an-mariesclaur",
            "first_name": "Rojhelia An Marie",
            "middle_name": "S.",
            "last_name": "Claur",
            "image": "1615964256-mam-roj.jpg",
            "email": "rsclaur@dswd.gov.ph",
            "position": "Social Welfare Officer III",
            "office": "Regional Rehabilitation Center  for Youth Head",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters in Social Work (University of the Philippines Open University, Los Banos, 2017)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Children Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Multi&ndash; Disciplinary Team (MDT) Approach in the Management of Child Abuse Cases</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Gender&ndash; Responsive Case Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Bio psychosocial Assessment</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Intervention Planning</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Case Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Social Case Study Report</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Helping Process and Problem Solving</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Evaluation and Termination of Cases</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 33,
            "category_id": 1,
            "slug": "clarissaopadio",
            "first_name": "Clarissa",
            "middle_name": "O.",
            "last_name": "Padio",
            "image": "1615964343-mam-claire.jpg",
            "email": "bbramos@dswd.gov.ph",
            "position": "Project Development Officer III",
            "office": "Standards Section Head",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Bachelor of Science in Social Work (Saint Louis University, 1991)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1.</strong> <strong>Children Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>ECCD Learning Resource Packages (LRPs)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Rights of the Child</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Child&rsquo;s Friendly Space</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Standards Development and Monitoring</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Guidelines on the Registration, Licensing and Accreditation (RLA) of the SWADs and SPs</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Guidelines on the issuance of Solicitation Permit</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Guidelines on the issuance of Certificate of Recognition to ECCD Workers</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Modules on Pre-marriage Counselling (PMC) Mode II</em></p>\r\n\t</li>\r\n</ul><p><strong>3. </strong><strong>Case Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Social Case Study</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Helping Process and problem solving</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Evaluation and Termination of Cases</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 34,
            "category_id": 2,
            "slug": "concepcionenavales",
            "first_name": "Concepcion",
            "middle_name": "E.",
            "last_name": "Navales",
            "image": "1615964468-mam-cion.jpg",
            "email": "cenavales@dswd.gov.ph",
            "position": "Social Welfare Officer IV",
            "office": "OIC Division Chief Protective Services Division",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p>Diploma in Social Work (9 units) University of Northern Philippines, 2005</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Women Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Case Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Protection for Women Against</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Gender-Based Violence</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Rights and Privileges for Solo Parents</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Community-based Programs for Women</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Youth</strong><strong> </strong><strong>Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Case Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Positive Discipline and Inquiry</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Gender Sensitivity Training (GST)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Youth Sector Regulatory (Registration,</em><em> </em><em>Licensing, Accreditation of NGOs and CSO Partnership)</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 35,
            "category_id": 2,
            "slug": "maria-ellaineelabasan",
            "first_name": "Maria Ellaine",
            "middle_name": "E.",
            "last_name": "Labasan",
            "image": "1615964551-mam-lala.jpg",
            "email": "meelabasan@dswd.gov.ph",
            "position": "Project Development Officer II",
            "office": "Gender and Development Focal- Pantawid Pamilyang Pilipino Program",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters of Social Work (18 units)</p><p>University of the Philippines Open University&ndash; Los Banos, 2015</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Women Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Women and Children&rsquo;s Rights</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Case Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Women Peace and Security</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Awareness on the concepts, content and implementation of the following laws on women:</em></p>\r\n\t</li>\r\n</ul><p><em>-</em><em>Republic Act 9208 also known as &ldquo;Anti&ndash; Trafficking in Persons Act of 2003&rdquo;</em></p><p><em>-Republic Act 9710 also known as</em><em> </em><em>&ldquo;Magna Karta of Women&rdquo;</em></p><p><em>-Republic Act 9262 also known as</em><em> </em><em>&ldquo;Anti&ndash; Violence Against Women and Their Children&rdquo;</em></p><p><strong>2. </strong><strong>Gender and Development</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Gender Sensitivity Training (GST)</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Gender&ndash; Based Violence</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Sexual Orientation, Gender Identity and Expressions (SOGIE)</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Gender Fair Language</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 36,
            "category_id": 3,
            "slug": "brendacconsolacion",
            "first_name": "Brenda",
            "middle_name": "C.",
            "last_name": "Consolacion",
            "image": "1615964619-mam-brenda.jpg",
            "email": "bcconsolacion@dswd.gov.ph",
            "position": "Project Development Officer III",
            "office": "Social Technology Section Head",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p>Masters in Public Administration<strong> </strong>(30 units) Baguio Colleges Foundation, 2004</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Community Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Community Driven Enterprise Development (CDED)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Guidance and assistance to indigenous peoples to organize themselves</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Community Decision&ndash; Making and Problem&ndash; Solving</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong> <strong>Business Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Financial Literacy</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Simple Bookkeeping</em></p>\r\n\t</li>\r\n</ul><p><strong>3. </strong><strong>Disaster Response and Mitigation</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Warehouse Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Relief Operations</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 37,
            "category_id": 3,
            "slug": "edelinedgenove",
            "first_name": "Edeline",
            "middle_name": "D.",
            "last_name": "Genove",
            "image": "1615964679-mam-edeline.jpg",
            "email": "edgonevel@dswd.gov.ph",
            "position": "Social Welfare Officer III",
            "office": "Adoption Resource and Referral Section Head; Minors Travelling Abroad Head",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p>Masters in Public Administration<strong> </strong>(30 units) Baguio Colleges Foundation, 2015</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong> <strong>Family Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Adoption</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Case Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Analysis and Assessment</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Social Protection</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Family Case</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Social Pension Program Implementation</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Republic Act 9994 also known as</em><em> </em><em>&ldquo;The Expanded Senior Citizen Act of 2010&rdquo;</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Administration of the Social Pension Pay-out</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 38,
            "category_id": 3,
            "slug": "mariatmadiguid",
            "first_name": "Maria",
            "middle_name": "T.",
            "last_name": "Madiguid",
            "image": "1615964924-mam-maria.jpg",
            "email": "mariamadiguid@yahoo.com",
            "position": "Project Development Officer III",
            "office": "Modified Cash Transfer Focal",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Bachelor of Science in Social Work (Saint Louis University, 2005)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Children and Youth Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Case Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Social Cost of Overseas Migration</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Filling Cases for the Protection of Children Against Child Abuse</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Gender Concepts and Gender Sensitivity</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Community Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Formation of Local Organizations</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Cooperation and collaboration with Various Groups and Organizations</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Stimulating the Active Participation of all Elements in the Community</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 39,
            "category_id": 3,
            "slug": "john-ericbescalante",
            "first_name": "John Eric",
            "middle_name": "B.",
            "last_name": "Escalante",
            "image": "1615965003-jeescalante.jpg",
            "email": "jebescalante@dswd.gov.ph",
            "position": "Project Development Officer III",
            "office": "Family Development Section Focal",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p><strong>1. </strong>Masters in Development Communication (University of the Philippines Open University- Los Banos, 2019)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Youth, Children, Family, and Community Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Positive Discipline in Everyday Parenting</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Parent Effectiveness Session</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Family Development Session</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Youth Development Sessions Module</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Population Awareness and Family Life Orientation Module</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Appreciating Early Child Education Module</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Social Marketing</strong></p><p><strong>3. </strong><strong>Partnership Building</strong></p></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 40,
            "category_id": 4,
            "slug": "libertineabalicdang",
            "first_name": "Libertine",
            "middle_name": "A.",
            "last_name": "Balicdang",
            "image": "1615965150-labalicdang.jpg",
            "email": "labalicdang@dswd.gov.ph",
            "position": "Social Welfare Officer IV",
            "office": "Community Based and Concurrent Sector Section Head",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters in Crisis and Disaster Risk Reduction Management (University of Baguio, 2019)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Older Persons Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Concepts and content of the Republic Act 9994 or also known as &ldquo;Expanded Senior Citizen Act of 2010&rdquo;</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Implementation of the Social Pension&nbsp; Program</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Persons with Disability Welfare</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Auxiliary Social Services for PWDs</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Concepts and content of the Republic Act 9442 or also known as &ldquo;Magna Carta for Disabled Persons, and for other purposes&rdquo;</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Batas Pambansa Blg. 344 or also known as &ldquo;Accessibility Law&rdquo;</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul><p><strong>Community Welfare</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Social Work Administration</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Community Organizing</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Community Driven Development</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Disaster Response and Management</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Critical Incident Stress Debriefing</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 41,
            "category_id": 4,
            "slug": "lornaclumian",
            "first_name": "Lorna",
            "middle_name": "C.",
            "last_name": "Lumian",
            "image": "1615965204-mam-lorna-2.jpg",
            "email": "lumioan30@gmail.com",
            "position": "Social Welfare Officer III",
            "office": "Pantawid Pamilyang Pilipino Program",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p>Masters of Science in Social Work<strong> </strong>(27 units) Philippine Women University, 2013</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Persons with Disabilities Welfare</strong></p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p><em>Concepts and Content of the Republic Act No. 7277 or also known as &ldquo;Magna Carta for Disable Persons&rdquo;</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>Case Management</em></p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p><em>General Knowledge on Disability</em></p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Community Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Social Work Administration</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Community Organizing</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Case Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Group Work</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 42,
            "category_id": 9,
            "slug": "enriquehgascon",
            "first_name": "Enrique",
            "middle_name": "H.",
            "last_name": "Gascon",
            "image": "1615965340-ehgascon.jpg",
            "email": "ehgascon@dswd.gov.ph",
            "position": "Chief Administrative Officer",
            "office": "OIC- Assistant Regional Director for Administration",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p><strong>1. </strong>Masters of Science in Global Information and Telecommunications Studies (Waseda University&ndash; Japan, 2012)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Information Communication Technology</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Data Mining</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Data Integration</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Data Warehousing</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Network Administration and Design</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Network Infrastructure</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Telecommunications Technologies</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Government Office Administration</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Government Procurement</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Employees Welfare and Benefits</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Office General Services</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Financial and Procurement Process</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 43,
            "category_id": 9,
            "slug": "ronilorflores",
            "first_name": "Ronilo",
            "middle_name": "R.",
            "last_name": "Flores",
            "image": "1615965395-rrfloresjpg.jpg",
            "email": "rrflores@dswd.gov.ph",
            "position": "Administrative Officer V",
            "office": "OIC Chief Human Resource Management and Development Division",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p>Masters in Public Administration<strong> </strong>(33 units) Baguio Central School</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Human Resource Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Recruitment, Selection and Placement (RSP)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Performance Management System (PMS)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Career Pathing Program</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Career Development Management System</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Code of Conduct</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Leave Administration</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Time Monitoring</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Conflict Resolution</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Mediation and Negotiation</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Administrative Procedures</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Job Analysis</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Job Alignment</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Competency&ndash; Based Job Description Development</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p>5S (Lean Management)</p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Advocacy on Human Immunodeficiency Virus (HIV) Prevention</strong></p></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 44,
            "category_id": 9,
            "slug": "rina-clairelreyes",
            "first_name": "Rina Claire",
            "middle_name": "L.",
            "last_name": "Reyes",
            "image": "1615965457-rclreyes.jpg",
            "email": "rclreyes@dswd.gov.ph",
            "position": "Supervising Administrative Officer",
            "office": "OIC Chief Administrative Division",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters of Public Management (24 Units) University of the Philippines (Open University) <em>*</em><em>Currently Enrolled</em></p><p><em><strong>Certifications:</strong></em></p><p><em>a. Lean Six Sigma White Belt Certified</em><em>&nbsp; </em><em>Management Strategy Institute</em><em>&nbsp; </em><em>Certification No. 47222534</em></p><p><em>b.Project Management</em><em>&nbsp;</em><em>Essentials Certified</em><em>&nbsp; </em><em>Management Strategy Institute</em><em>&nbsp; </em><em>Certification No. 47222535</em></p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Government Accounting</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Fundamentals of Government Expenditures</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Income Taxation</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Procurement Procedures</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Bookkeeping</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Financial Accounting</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Cash Management and Control</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Disbursement and Fiscal Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Financial Transactions</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Financial Statement Reporting</em></p>\r\n\t</li>\r\n</ul><p><strong>3. </strong><strong>Procurement</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Public Procurement</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Bids and Awards Deliberation</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 45,
            "category_id": 9,
            "slug": "julieagascon",
            "first_name": "Julie",
            "middle_name": "A.",
            "last_name": "Gascon",
            "image": "1615965520-jagascon.jpg",
            "email": "jagascon@dswd.gov.ph",
            "position": "Personnel Administrative Section Head",
            "office": "Administrative Officer V",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters in Public Administration (Baguio Central University, 2016)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Financial Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Cash Management and Control</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Disbursement and Fiscal Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Financial Transactions</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Financial Report or Statement</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Human Resource Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Code of Conduct</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Leave Administration</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Time Monitoring</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Administrative Procedures</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Office General Services</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 46,
            "category_id": 9,
            "slug": "lany-lizelgdiaz",
            "first_name": "Lany Lizel",
            "middle_name": "G.",
            "last_name": "Diaz",
            "image": "1615965599-llzdiaz.jpg",
            "email": "llgdiaz@dswd.gov.ph",
            "position": "Administrative Officer V",
            "office": null,
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Bachelor of Science in Accountancy (Saint Louis University, 2003)</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Operations Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Property, Supply and Warehouse</em><em>&nbsp;</em><em>Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Preparation of PPMP for Office Supplies and Equipment</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Supply and Property Management</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Procurement Procedures</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Purchase Requisition and Review of Request</em><em>&nbsp;</em><em>Quotation Request</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Negotiation and Contract</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Receive Goods and three-way matching</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Invoice Approval Payment</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Records Keeping</em></p>\r\n\t</li>\r\n</ul><p><strong>3. </strong><strong>Cash Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Disbursement</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Financial Report or Statement</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 47,
            "category_id": 9,
            "slug": "eleonorbayan",
            "first_name": "Eleonor",
            "middle_name": "B.",
            "last_name": "Ayan",
            "image": "1615965671-ebayan.jpg",
            "email": "ebayan@dswd.gov.ph",
            "position": "Nutritionist Dietitian III",
            "office": "Supplementary Feeding Program Section Head",
            "content": "<p><em><strong>Highest Educational Attainment:</strong></em><p>Masters in Community Health Development<strong> </strong>(30units); Benguet State University (Open University), 2016</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Nutrition and Dietetics</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Diabetes Awareness and Education</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Therapeutic and Special Diet</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Nutrition Program Planning</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Children and Solo Parent Welfare</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Early Child Care and Development (ECCD)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Rights of the Child</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Parent Effectiveness</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Strengthening of Family Values and</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Preservation of Cultural Heritage</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 48,
            "category_id": 9,
            "slug": "norieccastaneda",
            "first_name": "Norie",
            "middle_name": "C.",
            "last_name": "Castaneda",
            "image": "1615965726-mam-norie.jpg",
            "email": "nccastaneda@dswd.gov.ph",
            "position": "Administrative Officer V",
            "office": "Budget Section Head",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters in Development Management<strong> </strong>(33units); University of the Cordilleras, 2019</p><p><em><strong>Specialization:</strong></em></p><p>Government Budgeting:</p><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>Budget Preparation, Execution, and Monitoring</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 49,
            "category_id": 9,
            "slug": "jerrydjulian",
            "first_name": "Jerry",
            "middle_name": "D.",
            "last_name": "Julian",
            "image": "1615965779-sir-jed.jpg",
            "email": "jdjulian@dswd.gov.ph",
            "position": "Training Specialist III",
            "office": "Capacity Building Section Head",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters in Public Administration<strong> </strong>(13 units) University of the Philippines&ndash; Diliman, 2015</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Talent Development</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Capacity Building</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Workplace Learning</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Talent Gap Assessment</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Leadership and Management</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Personal Branding</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Learning Facilitation</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Events Management</p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Knowledge Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Innovation</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Integrated Library System</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Learning Intervention Design and Development</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Module Development</p>\r\n\t</li>\r\n\t<li>\r\n\t<p>Good Practice Documentation</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 50,
            "category_id": 9,
            "slug": "kathleen-gloryc-david",
            "first_name": "Kathleen Glory",
            "middle_name": "C. David",
            "last_name": null,
            "image": "1615965846-mam-kath.jpg",
            "email": "kgvcasuga@dswd.gov.ph",
            "position": "Administrative Officer IV",
            "office": "Human Resource and Welfare Section Head",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters in Guidance and Counselling<strong> </strong>(13units); University of the Cordilleras, 2013</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Human Resource Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Recruitment, Selection and Placement (RSP)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Performance Management System (PMS)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Rewards and Recognition</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Employee Welfare</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 51,
            "category_id": 9,
            "slug": "jessey-reyfrios",
            "first_name": "Jessey Rey",
            "middle_name": "F.",
            "last_name": "Rios",
            "image": "1615965912-sir-jesse.jpg",
            "email": "jfrios@dswd.gov.ph",
            "position": "Management Audit Analyst II",
            "office": "Internal Audit Unit",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Juris Doctor (University of Baguio, 2019)</p><p><em><strong>Specialization:</strong></em></p><ol>\r\n\t<li>\r\n\t<p><strong>Internal Auditing and Internal Control System:</strong></p>\r\n\t</li>\r\n</ol><ul>\r\n\t<li>\r\n\t<ul>\r\n\t\t<li>\r\n\t\t<p>Operations Audit</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>Management Audit</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>Compliance Audit</p>\r\n\t\t</li>\r\n\t\t<li>\r\n\t\t<p>System Analysis and Design</p>\r\n\t\t</li>\r\n\t</ul>\r\n\t</li>\r\n</ul><ol>\r\n\t<li>\r\n\t<p><strong>Disaster Risk Reduction Management</strong></p>\r\n\t</li>\r\n</ol><ul>\r\n\t<li>\r\n\t<p>Incident Command System</p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 52,
            "category_id": 9,
            "slug": "nerizza-fayevtrinidad",
            "first_name": "Nerizza Faye",
            "middle_name": "V.",
            "last_name": "Trinidad",
            "image": "1615965978-nfvtrinidad.jpg",
            "email": "nfgvillanueva@dswd.gov.ph",
            "position": "Regional Information Officer II",
            "office": "Social Marketing Unit Head",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters in Human Resource Management (18units); Benguet State University, 2011</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Social Marketing, Advocacy and</strong><strong> </strong><strong>Communications</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Crisis Communication</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Speech Communication</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>DSWD Messaging and Branding Guidelines</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Social Marketing, Advocacy, Networking, and Resource Generation</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Community Radio</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>News, Feature and Broadcast Writing</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Social Technologies</strong></p><p><strong>3. </strong><strong>Knowledge Management</strong></p><p><strong>4. </strong><strong>Hosting and Emceeing</strong></p></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 53,
            "category_id": 9,
            "slug": "jamesgdocog",
            "first_name": "James",
            "middle_name": "G.",
            "last_name": "Docog",
            "image": "1615966033-jgdocog.jpg",
            "email": "jgdocog@dswd.gov.ph",
            "position": "Administrative Officer II",
            "office": "Personnel Administration Section",
            "content": "<p><em><strong>Highest Educational Background:</strong></em><p>Masters in Language and Literature<strong> </strong>(24units) University of the Cordilleras, 2019</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Personnel Administration</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Compensation and Benefits</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Personnel Records Management</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Requisition and Utilization of Personnel</em><em>&nbsp;</em><em>Services</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Policies Governing Personnel Administration</em></p>\r\n\t</li>\r\n</ul><p><strong>2. </strong><strong>Language Literature</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Teaching Literature</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Teaching Language</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>4 Basic Language Skills (Reading, Speaking, Writing, and Listening)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Theories on Language and Literature</em></p>\r\n\t</li>\r\n</ul><p><strong>3. </strong><strong>Broadcast Production</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Video and Audio Production Technologies</em></p>\r\n\t</li>\r\n</ul><p><strong>4. </strong><strong>News and Feature Writing</strong></p></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        },
        {
            "id": 54,
            "category_id": 9,
            "slug": "shamahsponasen",
            "first_name": "Shamah",
            "middle_name": "S.",
            "last_name": "Ponasen",
            "image": "1615966086-ssponasan.jpg",
            "email": "sdsicuan@dswd.gov.ph",
            "position": "Statistician I",
            "office": "Policy Development and Planning Section",
            "content": "<p><strong>Highest Educational Background:</strong><p>Bachelor of Science in Applied Statistics Benguet State University</p><p><em><strong>Specialization:</strong></em></p><p><strong>1. </strong><strong>Basic Statistics</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Population and Sample</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Types of Measurement</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Descriptive Statistics</em></p>\r\n\t</li>\r\n</ul><p><em>-Measures of Central Tendency</em></p><p><em>-Measures of Spread</em></p><ul>\r\n\t<li>\r\n\t<p><em>Inferential Statistics</em></p>\r\n\t</li>\r\n</ul><p><em>-Population and Sample</em></p><p><strong>2.</strong> <strong>Human Resource Management</strong></p><ul>\r\n\t<li>\r\n\t<p><em>Recruitment, Selection and Placement (RSP)</em></p>\r\n\t</li>\r\n\t<li>\r\n\t<p><em>Performance Management System (PMS)</em></p>\r\n\t</li>\r\n</ul></p>\n",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null
        }
    ]';
        $data = json_decode($data,true);
        DB::table('dir_expertise')->insert($data);
    }
}
